### ISSUE TITLE
Performance

### ISSUE THREAD

**Issue by paked** [Newbrict/engi#8]
It has been found that on OSX (source @paked) and at least arch linux (source: @Newbrict) engi goes into what can only be described as a radical panic state when it is moved out of the main workspace (or taken out of focus). Usually after a few minutes it begins chewing up vast amounts of (presumably) CPU. During this phase, collision also seems to deactivate/not take effect. This is not confirmed on Windows (would love some confirmation xD please Windows users)

**Comment by Newbrict** [comment]
sick
